[project]
name = "coordinadorapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dlt>=1.4.1",
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
    "streamlit>=1.40.2",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
